sudo: required
services:
  - docker

before_install:
  - docker build -t myidalias/experiment-test -f Dockerfile.dev .

script:
  - docker run myidalias/experiment-test npm test -- --coverage

after_success:
  - docker build -t myidalias/experiment .
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push myidalias/experiment

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: complex-docker
  env: ComplexDocker-env
  bucket_name: elasticbeanstalk-us-east-1-382498021366

  bucket_path: complex-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ON_TRAVISCI
  secret_access_key:
    secure: $AWS_SECRET_KEY_ON_TRAVISCI
